# Generated by Django 4.0.6 on 2022-08-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('paperhight', models.IntegerField(default=10)),
                ('paperwidth', models.IntegerField(default=10)),
            ],
        ),
    ]
