# Generated by Django 4.1 on 2022-08-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sefer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="bottom",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="order",
            name="chapfontsize",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="order",
            name="engfont",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="evenhead",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="fontsize",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="order",
            name="headpos",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="hebboldfont",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="hebfont",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="inner",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="order",
            name="layout",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="newpage",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="order",
            name="oddhead",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="outer",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="order",
            name="pagenumheb",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="order",
            name="pagenumloc",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="parskip",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="order",
            name="spacing",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="order",
            name="top",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="order",
            name="translation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="text",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
