# Generated by Django 4.1 on 2022-08-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_remove_order_bottom_remove_order_chapfontsize_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sefer",
            name="book",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="sefer",
            name="translation",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
