# Generated by Django 4.1 on 2022-08-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_rename_translation_sefer_primary_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrimaryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="we have a mistake here", max_length=50),
                ),
            ],
        ),
    ]
