# Generated by Django 4.1 on 2022-08-28 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_secondarycategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="TertiaryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="we have a mistake here", max_length=50),
                ),
                (
                    "primary_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondary_category",
                        to="website.secondarycategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuaternaryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="we have a mistake here", max_length=50),
                ),
                (
                    "primary_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondary_category",
                        to="website.tertiarycategory",
                    ),
                ),
            ],
        ),
    ]
