# Generated by Django 4.1 on 2022-08-28 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_tertiarycategory_quaternarycategory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quaternarycategory",
            old_name="primary_category",
            new_name="level_three",
        ),
        migrations.RenameField(
            model_name="secondarycategory",
            old_name="primary_category",
            new_name="level_one",
        ),
        migrations.RenameField(
            model_name="tertiarycategory",
            old_name="primary_category",
            new_name="level_two",
        ),
    ]
