# Generated by Django 4.1 on 2022-08-28 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "website",
            "0009_rename_primary_category_quaternarycategory_level_three_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="quaternarycategory",
            old_name="level_three",
            new_name="category_three",
        ),
        migrations.RenameField(
            model_name="secondarycategory",
            old_name="level_one",
            new_name="primary_category",
        ),
        migrations.RenameField(
            model_name="tertiarycategory",
            old_name="level_two",
            new_name="category_two",
        ),
    ]
