# Generated by Django 4.1 on 2022-08-31 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "website",
            "0010_rename_level_three_quaternarycategory_category_three_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="category_1",
            field=models.ForeignKey(
                default= 1,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.primarycategory",
            ),
        ),
    ]
