# Generated by Django 4.1 on 2022-09-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0011_order_category_1"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="category_1",
        ),
    ]
