# Generated by Django 4.1 on 2022-09-12 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0012_remove_order_category_1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quaternarycategory",
            name="category_three",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quaternary_category",
                to="website.tertiarycategory",
            ),
        ),
        migrations.AlterField(
            model_name="tertiarycategory",
            name="category_two",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tertiary_category",
                to="website.secondarycategory",
            ),
        ),
    ]
