# Generated by Django 4.1 on 2022-09-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0013_alter_quaternarycategory_category_three_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="primarycategory",
            name="name",
            field=models.CharField(default="we have a miss here", max_length=50),
        ),
        migrations.AlterField(
            model_name="quaternarycategory",
            name="name",
            field=models.CharField(default="we have a miss here", max_length=50),
        ),
        migrations.AlterField(
            model_name="secondarycategory",
            name="name",
            field=models.CharField(default="we have a miss here", max_length=50),
        ),
        migrations.AlterField(
            model_name="tertiarycategory",
            name="name",
            field=models.CharField(default="we have a miss here", max_length=50),
        ),
    ]
