# Generated by Django 4.1 on 2022-09-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0014_alter_primarycategory_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Translations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translation", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
