# Generated by Django 4.1 on 2022-09-12 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0015_translations"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Translations",
        ),
    ]
