# Generated by Django 4.1 on 2022-11-06 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0020_sefer_prime_cat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sefer",
            name="prime_cat",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prime_cat",
                to="website.primarycategory",
            ),
        ),
    ]
