# Generated by Django 4.1 on 2022-11-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0023_alter_sefer_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sefer",
            name="book",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
