# Generated by Django 4.1 on 2022-11-10 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0024_alter_sefer_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="sefer",
            name="secondary_cat",
            field=models.ForeignKey(
                blank=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="secondary_cat",
                to="website.secondarycategory",
            ),
        ),
    ]
