# Generated by Django 4.1 on 2022-11-17 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0025_sefer_secondary_cat"),
    ]

    operations = [
        migrations.AddField(
            model_name="sefer",
            name="quaternary_cat",
            field=models.ForeignKey(
                blank=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quaternary_cat",
                to="website.quaternarycategory",
            ),
        ),
        migrations.AddField(
            model_name="sefer",
            name="tertiary_cat",
            field=models.ForeignKey(
                blank=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tertiary_cat",
                to="website.tertiarycategory",
            ),
        ),
    ]
