# Generated by Django 4.1 on 2022-11-20 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0026_sefer_quaternary_cat_sefer_tertiary_cat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sefer",
            name="primary_category",
        ),
        migrations.RemoveField(
            model_name="sefer",
            name="quaternary_cat",
        ),
        migrations.RemoveField(
            model_name="sefer",
            name="tertiary_cat",
        ),
    ]
