# Generated by Django 4.1 on 2022-11-20 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0029_remove_sefer_quaternary_cat_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sefer",
            name="id",
        ),
        migrations.AddField(
            model_name="sefer",
            name="quaternary_cat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quaternary_cat",
                to="website.quaternarycategory",
            ),
        ),
        migrations.AddField(
            model_name="sefer",
            name="tertiary_cat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tertiary_cat",
                to="website.tertiarycategory",
            ),
        ),
        migrations.AlterField(
            model_name="quaternarycategory",
            name="category_three",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quaternary_category",
                to="website.tertiarycategory",
            ),
        ),
        migrations.AlterField(
            model_name="sefer",
            name="book",
            field=models.CharField(
                blank=True, max_length=100, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="tertiarycategory",
            name="category_two",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tertiary_category",
                to="website.secondarycategory",
            ),
        ),
    ]
